spring.application.name=Car_Service_Project
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/car_maintenance?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false


user.default-user.username=administrator
user.default-user.password=123456
user.default-user.firstName=Admin
user.default-user.lastName=Admin
user.default-user.email=admin@car-service.com
user.default-user.role=ADMIN
user.default-user.class-type=NEW
user.default-user.active=true

user.guest-user.username=guest
user.guest-user.password=guest123
user.guest-user.first-name=Guest
user.guest-user.last-name=User
user.guest-user.email=guest@car-service.com
user.guest-user.role=GUEST
user.guest-user.class-type=NEW
user.guest-user.active=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=n.p.noev@gmail.com
spring.mail.password=vuhz pfho ogbc uepr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true